# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Genetic Programming Theory & Practice Workshops"
email: bill@vagueinnovation.com
description: >
  Support for attendees of the Annual GPTP Workshops.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gptp-workshop.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems: ['kramdown']
exclude: ['config.ru', 'vendor','Gemfile', 'Gemfile.lock',  'Rakefile', 'README.md']

plugins:
  - jekyll-last-modified-at

last-modified-at:
    date-format: '%d-%b-%y'